import type { Metadata } from "next";
import { ViewTransition } from "react";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  //비동기로 해서 await로 cookies를 읽을때까지 RootLayout대기
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 서버가 쿠키에서 로그인 여부를 미리 읽어 Provider에 전달 (첫 화면 깜빡임 방지)
  // 혹시 모를 쿠키 읽기 실패에 대비해 기본값 false로 안전하게 처리
  let initialLoggedIn = false;
  try {
    const cookieStore = await cookies(); //await로 읽을때까지 RootLayout대기
    initialLoggedIn = cookieStore.get("loggedIn")?.value === "1";
  } catch {
    initialLoggedIn = false;
  }

  return (
    // dark 클래스를 항상 붙여서 OS 테마와 무관하게 다크 화면으로 고정
    <html
      lang="ko"
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-50 text-black dark:bg-black dark:text-zinc-50">
        <AuthProvider initialLoggedIn={initialLoggedIn}>
          <ViewTransition default="page-fade-slide">{children}</ViewTransition>
        </AuthProvider>
      </body>
    </html>
  );
}
